/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardExamplesRouteImport } from './routes/dashboard.examples'
import { Route as ApiV1RunnersRouteImport } from './routes/api/v1/runners'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1RunnersSplatRouteImport } from './routes/api/v1/runners/$'
import { Route as ApiV1RunnerConnectRouteImport } from './routes/api/v1/runner/connect'
import { Route as ApiV1RunnerOperationRouteImport } from './routes/api/v1/runner/$operation'
import { Route as ApiV1MessagesOrnnMessageIdRouteImport } from './routes/api/v1/messages/$ornnMessageId'
import { Route as ApiV1JobsJobIdRouteImport } from './routes/api/v1/jobs/$jobId'
import { Route as ApiV1GithubWebhookRouteImport } from './routes/api/v1/github/webhook'
import { Route as ApiV1RunnerSetupSplatRouteImport } from './routes/api/v1/runner/setup/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExamplesRoute = DashboardExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiV1RunnersRoute = ApiV1RunnersRouteImport.update({
  id: '/api/v1/runners',
  path: '/api/v1/runners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunnersSplatRoute = ApiV1RunnersSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiV1RunnersRoute,
} as any)
const ApiV1RunnerConnectRoute = ApiV1RunnerConnectRouteImport.update({
  id: '/api/v1/runner/connect',
  path: '/api/v1/runner/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunnerOperationRoute = ApiV1RunnerOperationRouteImport.update({
  id: '/api/v1/runner/$operation',
  path: '/api/v1/runner/$operation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MessagesOrnnMessageIdRoute =
  ApiV1MessagesOrnnMessageIdRouteImport.update({
    id: '/api/v1/messages/$ornnMessageId',
    path: '/api/v1/messages/$ornnMessageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1JobsJobIdRoute = ApiV1JobsJobIdRouteImport.update({
  id: '/api/v1/jobs/$jobId',
  path: '/api/v1/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GithubWebhookRoute = ApiV1GithubWebhookRouteImport.update({
  id: '/api/v1/github/webhook',
  path: '/api/v1/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunnerSetupSplatRoute = ApiV1RunnerSetupSplatRouteImport.update({
  id: '/api/v1/runner/setup/$',
  path: '/api/v1/runner/setup/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/examples': typeof DashboardExamplesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/runners': typeof ApiV1RunnersRouteWithChildren
  '/api/v1/github/webhook': typeof ApiV1GithubWebhookRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/messages/$ornnMessageId': typeof ApiV1MessagesOrnnMessageIdRoute
  '/api/v1/runner/$operation': typeof ApiV1RunnerOperationRoute
  '/api/v1/runner/connect': typeof ApiV1RunnerConnectRoute
  '/api/v1/runners/$': typeof ApiV1RunnersSplatRoute
  '/api/v1/runner/setup/$': typeof ApiV1RunnerSetupSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/examples': typeof DashboardExamplesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/runners': typeof ApiV1RunnersRouteWithChildren
  '/api/v1/github/webhook': typeof ApiV1GithubWebhookRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/messages/$ornnMessageId': typeof ApiV1MessagesOrnnMessageIdRoute
  '/api/v1/runner/$operation': typeof ApiV1RunnerOperationRoute
  '/api/v1/runner/connect': typeof ApiV1RunnerConnectRoute
  '/api/v1/runners/$': typeof ApiV1RunnersSplatRoute
  '/api/v1/runner/setup/$': typeof ApiV1RunnerSetupSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/examples': typeof DashboardExamplesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/runners': typeof ApiV1RunnersRouteWithChildren
  '/api/v1/github/webhook': typeof ApiV1GithubWebhookRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/messages/$ornnMessageId': typeof ApiV1MessagesOrnnMessageIdRoute
  '/api/v1/runner/$operation': typeof ApiV1RunnerOperationRoute
  '/api/v1/runner/connect': typeof ApiV1RunnerConnectRoute
  '/api/v1/runners/$': typeof ApiV1RunnersSplatRoute
  '/api/v1/runner/setup/$': typeof ApiV1RunnerSetupSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/examples'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/v1/runners'
    | '/api/v1/github/webhook'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/messages/$ornnMessageId'
    | '/api/v1/runner/$operation'
    | '/api/v1/runner/connect'
    | '/api/v1/runners/$'
    | '/api/v1/runner/setup/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/examples'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/v1/runners'
    | '/api/v1/github/webhook'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/messages/$ornnMessageId'
    | '/api/v1/runner/$operation'
    | '/api/v1/runner/connect'
    | '/api/v1/runners/$'
    | '/api/v1/runner/setup/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/examples'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/v1/runners'
    | '/api/v1/github/webhook'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/messages/$ornnMessageId'
    | '/api/v1/runner/$operation'
    | '/api/v1/runner/connect'
    | '/api/v1/runners/$'
    | '/api/v1/runner/setup/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1RunnersRoute: typeof ApiV1RunnersRouteWithChildren
  ApiV1GithubWebhookRoute: typeof ApiV1GithubWebhookRoute
  ApiV1JobsJobIdRoute: typeof ApiV1JobsJobIdRoute
  ApiV1MessagesOrnnMessageIdRoute: typeof ApiV1MessagesOrnnMessageIdRoute
  ApiV1RunnerOperationRoute: typeof ApiV1RunnerOperationRoute
  ApiV1RunnerConnectRoute: typeof ApiV1RunnerConnectRoute
  ApiV1RunnerSetupSplatRoute: typeof ApiV1RunnerSetupSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/examples': {
      id: '/dashboard/examples'
      path: '/examples'
      fullPath: '/dashboard/examples'
      preLoaderRoute: typeof DashboardExamplesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/v1/runners': {
      id: '/api/v1/runners'
      path: '/api/v1/runners'
      fullPath: '/api/v1/runners'
      preLoaderRoute: typeof ApiV1RunnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/runners/$': {
      id: '/api/v1/runners/$'
      path: '/$'
      fullPath: '/api/v1/runners/$'
      preLoaderRoute: typeof ApiV1RunnersSplatRouteImport
      parentRoute: typeof ApiV1RunnersRoute
    }
    '/api/v1/runner/connect': {
      id: '/api/v1/runner/connect'
      path: '/api/v1/runner/connect'
      fullPath: '/api/v1/runner/connect'
      preLoaderRoute: typeof ApiV1RunnerConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/runner/$operation': {
      id: '/api/v1/runner/$operation'
      path: '/api/v1/runner/$operation'
      fullPath: '/api/v1/runner/$operation'
      preLoaderRoute: typeof ApiV1RunnerOperationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/messages/$ornnMessageId': {
      id: '/api/v1/messages/$ornnMessageId'
      path: '/api/v1/messages/$ornnMessageId'
      fullPath: '/api/v1/messages/$ornnMessageId'
      preLoaderRoute: typeof ApiV1MessagesOrnnMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jobs/$jobId': {
      id: '/api/v1/jobs/$jobId'
      path: '/api/v1/jobs/$jobId'
      fullPath: '/api/v1/jobs/$jobId'
      preLoaderRoute: typeof ApiV1JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/github/webhook': {
      id: '/api/v1/github/webhook'
      path: '/api/v1/github/webhook'
      fullPath: '/api/v1/github/webhook'
      preLoaderRoute: typeof ApiV1GithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/runner/setup/$': {
      id: '/api/v1/runner/setup/$'
      path: '/api/v1/runner/setup/$'
      fullPath: '/api/v1/runner/setup/$'
      preLoaderRoute: typeof ApiV1RunnerSetupSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardExamplesRoute: typeof DashboardExamplesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardExamplesRoute: DashboardExamplesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiV1RunnersRouteChildren {
  ApiV1RunnersSplatRoute: typeof ApiV1RunnersSplatRoute
}

const ApiV1RunnersRouteChildren: ApiV1RunnersRouteChildren = {
  ApiV1RunnersSplatRoute: ApiV1RunnersSplatRoute,
}

const ApiV1RunnersRouteWithChildren = ApiV1RunnersRoute._addFileChildren(
  ApiV1RunnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1RunnersRoute: ApiV1RunnersRouteWithChildren,
  ApiV1GithubWebhookRoute: ApiV1GithubWebhookRoute,
  ApiV1JobsJobIdRoute: ApiV1JobsJobIdRoute,
  ApiV1MessagesOrnnMessageIdRoute: ApiV1MessagesOrnnMessageIdRoute,
  ApiV1RunnerOperationRoute: ApiV1RunnerOperationRoute,
  ApiV1RunnerConnectRoute: ApiV1RunnerConnectRoute,
  ApiV1RunnerSetupSplatRoute: ApiV1RunnerSetupSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
