/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1RunnerOperationRouteImport } from './routes/api/v1/runner/$operation'
import { Route as ApiV1MessagesOrnnMessageIdRouteImport } from './routes/api/v1/messages/$ornnMessageId'
import { Route as ApiV1JobsJobIdRouteImport } from './routes/api/v1/jobs/$jobId'
import { Route as ApiV1GithubWebhookRouteImport } from './routes/api/v1/github/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunnerOperationRoute = ApiV1RunnerOperationRouteImport.update({
  id: '/api/v1/runner/$operation',
  path: '/api/v1/runner/$operation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MessagesOrnnMessageIdRoute =
  ApiV1MessagesOrnnMessageIdRouteImport.update({
    id: '/api/v1/messages/$ornnMessageId',
    path: '/api/v1/messages/$ornnMessageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1JobsJobIdRoute = ApiV1JobsJobIdRouteImport.update({
  id: '/api/v1/jobs/$jobId',
  path: '/api/v1/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GithubWebhookRoute = ApiV1GithubWebhookRouteImport.update({
  id: '/api/v1/github/webhook',
  path: '/api/v1/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/v1/github/webhook': typeof ApiV1GithubWebhookRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/messages/$ornnMessageId': typeof ApiV1MessagesOrnnMessageIdRoute
  '/api/v1/runner/$operation': typeof ApiV1RunnerOperationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/v1/github/webhook': typeof ApiV1GithubWebhookRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/messages/$ornnMessageId': typeof ApiV1MessagesOrnnMessageIdRoute
  '/api/v1/runner/$operation': typeof ApiV1RunnerOperationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/v1/github/webhook': typeof ApiV1GithubWebhookRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/messages/$ornnMessageId': typeof ApiV1MessagesOrnnMessageIdRoute
  '/api/v1/runner/$operation': typeof ApiV1RunnerOperationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/v1/github/webhook'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/messages/$ornnMessageId'
    | '/api/v1/runner/$operation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/v1/github/webhook'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/messages/$ornnMessageId'
    | '/api/v1/runner/$operation'
  id:
    | '__root__'
    | '/'
    | '/api/v1/github/webhook'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/messages/$ornnMessageId'
    | '/api/v1/runner/$operation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiV1GithubWebhookRoute: typeof ApiV1GithubWebhookRoute
  ApiV1JobsJobIdRoute: typeof ApiV1JobsJobIdRoute
  ApiV1MessagesOrnnMessageIdRoute: typeof ApiV1MessagesOrnnMessageIdRoute
  ApiV1RunnerOperationRoute: typeof ApiV1RunnerOperationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/runner/$operation': {
      id: '/api/v1/runner/$operation'
      path: '/api/v1/runner/$operation'
      fullPath: '/api/v1/runner/$operation'
      preLoaderRoute: typeof ApiV1RunnerOperationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/messages/$ornnMessageId': {
      id: '/api/v1/messages/$ornnMessageId'
      path: '/api/v1/messages/$ornnMessageId'
      fullPath: '/api/v1/messages/$ornnMessageId'
      preLoaderRoute: typeof ApiV1MessagesOrnnMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jobs/$jobId': {
      id: '/api/v1/jobs/$jobId'
      path: '/api/v1/jobs/$jobId'
      fullPath: '/api/v1/jobs/$jobId'
      preLoaderRoute: typeof ApiV1JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/github/webhook': {
      id: '/api/v1/github/webhook'
      path: '/api/v1/github/webhook'
      fullPath: '/api/v1/github/webhook'
      preLoaderRoute: typeof ApiV1GithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiV1GithubWebhookRoute: ApiV1GithubWebhookRoute,
  ApiV1JobsJobIdRoute: ApiV1JobsJobIdRoute,
  ApiV1MessagesOrnnMessageIdRoute: ApiV1MessagesOrnnMessageIdRoute,
  ApiV1RunnerOperationRoute: ApiV1RunnerOperationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
